### ISSUE TITLE
.junorc.json seems to not be read in latest version

### ISSUE THREAD

**Issue by juanfcocontreras** [uetchy/juno#7]
When I updated to Juno 0.4, I got this error message:

```
A Java Script error ocurred in the main process

Uncaught Exception:
Error: spawn /usr/local/bin/jupyter-notebook ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

My .junorc.json is the same as in version before, but jupyterCommand (/usr/local/anaconda3/bin/jupyter-notebook) seems to be ignored, and default one is being used (/usr/local/bin/jupyter-notebook):

```
{
  "jupyterCommand": "/usr/local/anaconda3/bin/jupyter-notebook",
  "jupyterPort": 8888,
  "jupyterHome": "~",
  "openBrowserOnStartup": true
}
```

**Comment by uetchy** [comment]
Thank you for the report! I'll take a look at it.

**Comment by uetchy** [comment]
Released https://github.com/uetchy/juno/releases/tag/v1.0.0
